export const badgeDict = {
  bug: "bg-green-500 text-white",
  dark: "bg-gray-800 text-white",
  dragon: "bg-blue-700 text-white",
  electric: "bg-yellow-500 text-black",
  fairy: "bg-pink-500 text-white",
  fighting: "bg-red-600 text-white",
  fire: "bg-orange-500 text-white",
  flying: "bg-blue-400 text-white",
  ghost: "bg-purple-500 text-white",
  grass: "bg-green-600 text-white",
  ground: "bg-yellow-700 text-white",
  ice: "bg-cyan-300 text-black",
  normal: "bg-white text-black",
  poison: "bg-purple-600 text-white",
  psychic: "bg-pink-400 text-white",
  rock: "bg-gray-700 text-white",
  steel: "bg-gray-400 text-black",
  water: "bg-blue-500 text-white",
};
export const nameDict = {
  bug: "Inseto",
  dark: "Sombrio",
  dragon: "Dragão",
  electric: "Elétrico",
  fairy: "Fada",
  fighting: "Lutador",
  fire: "Fogo",
  flying: "Voador",
  ghost: "Fantasma",
  grass: "Planta",
  ground: "Terrestre",
  ice: "Gelo",
  normal: "Normal",
  poison: "Veneno",
  psychic: "Psíquico",
  rock: "Pedra",
  steel: "Aço",
  water: "Água",
};
export const pageDict = {
  bug: "bg-green-100",
  dark: "bg-gray-800",
  dragon: "bg-blue-100",
  electric: "bg-yellow-100",
  fairy: "bg-pink-100",
  fighting: "bg-red-100",
  fire: "bg-orange-100",
  flying: "bg-blue-200",
  ghost: "bg-purple-100",
  grass: "bg-green-200",
  ground: "bg-yellow-200",
  ice: "bg-cyan-100",
  normal: "bg-white",
  poison: "bg-purple-200",
  psychic: "bg-pink-200",
  rock: "bg-gray-200",
  steel: "bg-gray-300",
  water: "bg-blue-300",
};
